import '@/styles/globals.scss'
import {Inter} from 'next/font/google'
import {Metadata} from "next";
import Providers from "@/context/Providers";
import {NavbarComponent} from "@/components/Navbar/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: {
    children: React.ReactNode
}): Promise<JSX.Element> {

    return (
        <html lang="ko">
        <body className={inter.className}>
        <Providers>
                <div className="wrap">
            <NavbarComponent/>
                    {children}
                </div>
        </Providers>
        </body>
        </html>
    )
}