import '@/styles/globals.scss'
import {Inter} from 'next/font/google'
import {Metadata} from "next";
import Providers from "@/components/context/Providers";
import GlobalNavbarComponent from "@/components/UI/NavbarGlobal/GlobalNavbarComponent";
import {FooterClientComponent} from "@/components/UI/Footer/Footer";
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = async ({children}: { children: React.ReactNode }): Promise<JSX.Element> => {
    return (
        <html lang="ko">
        <body>
        <Providers>
            <GlobalNavbarComponent/>
            {children}
            <FooterClientComponent/>
        </Providers>
        </body>
        </html>
    )
}

export default RootLayout;